apiVersion: 1

contactPoints:
  - orgId: 1
    name: alertmanager
    receivers:
      - uid: alertmanager-webhook
        type: webhook
        settings:
          url: "http://alertmanager:9093/api/v2/alerts"
          httpMethod: POST

policies:
  - orgId: 1
    receiver: alertmanager
    group_by: ["alertname", "grafana_folder"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: slack
        match:
          severity: critical
        continue: true
      - receiver: email
        match:
          severity: critical
        continue: true
