apiVersion: 1

contactPoints:
  - orgId: 1
    name: email
    receivers:
      - uid: email-ops
        type: email
        settings:
          addresses: "${ALERT_EMAIL_TO:-ops@vigilagent.dev}"
          singleEmail: false
        disableResolveMessage: false
